
name: NASA PROJECT CI
# we want to build the project every time we update the code
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client

  # deploy:
  #   needs: build