
name: NASA PROJECT CI
# we want to build the project every time we update the code
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
  # this is for github to detect that we are running in a continuous integration environment and it will disable watch mode
    env:
      CI: true
    strategy:
      matrix: 
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test

  # deploy:
  #   needs: build